### ISSUE TITLE
Breaks Angular storybook build step when included in devDependencies 

### ISSUE THREAD

**Issue by josh803316** [sweepline/eslint-plugin-unused-imports#49]
# Please follow the general troubleshooting steps first:

When we include this package in our devDependencies and try to build angular storybook we get the following:

- When we remove it from our dependencies this step works

```bash
pnpx sb init --type angular
...
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "from" argument must be of type string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2022-10-19T22_29_12_096Z-debug-0.log
An error occurred while installing dependencies.

 ERROR  Command failed with exit code 1: /home/ec2-user/.local/share/pnpm/store/v3/tmp/dlx-13665/node_modules/.bin/sb init --type angular

pnpm: Command failed with exit code 1: /home/ec2-user/.local/share/pnpm/store/v3/tmp/dlx-13665/node_modules/.bin/sb init --type angular
    at makeError (/home/ec2-user/setup-pnpm/node_modules/.pnpm/pnpm@7.13.5/node_modules/pnpm/dist/pnpm.cjs:22440:17)
    at handlePromise (/home/ec2-user/setup-pnpm/node_modules/.pnpm/pnpm@7.13.5/node_modules/pnpm/dist/pnpm.cjs:23011:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/ec2-user/setup-pnpm/node_modules/.pnpm/pnpm@7.13.5/node_modules/pnpm/dist/pnpm.cjs:188098:7)
    at async /home/ec2-user/setup-pnpm/node_modules/.pnpm/pnpm@7.13.5/node_modules/pnpm/dist/pnpm.cjs:195322:21
    at async main (/home/ec2-user/setup-pnpm/node_modules/.pnpm/pnpm@7.13.5/node_modules/pnpm/dist/pnpm.cjs:195293:34)
    at async runPnpm (/home/ec2-user/setup-pnpm/node_modules/.pnpm/pnpm@7.13.5/node_modules/pnpm/dist/pnpm.cjs:195487:5)
    at async /home/ec2-user/setup-pnpm/node_modules/.pnpm/pnpm@7.13.5/node_modules/pnpm/dist/pnpm.cjs:1954[79](https://github.com/sketchy/core-web/actions/runs/3285406861/jobs/5412466987#step:15:80):7
```

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

**Comment by josh803316** [comment]
Looks like this issue was not this package:
https://github.com/npm/cli/issues/4907

I removed the package-lock.json from our repo and that seemed to fix it.
