### ISSUE TITLE
cjs/esm bunding is screwy `Error: Dynamic require of "eslint" is not supported` 

### ISSUE THREAD

**Issue by jessekrubin** [sweepline/eslint-plugin-unused-imports#95]
esm/cjs bundles are screwy...

Just upgraded got this message...

```
Oops! Something went wrong! :(

ESLint: 9.8.0

Error: Dynamic require of "eslint" is not supported
    at file:///D:/geobox/node_modules/.pnpm/eslint-plugin-unused-imports@4.1.1_@typescript-eslint+eslint-plugin@8.0.1_@typescript-eslint+_cdfts5mwz3dmzs6enchjkop4n4/node_modules/eslint-plugin-unused-imports/dist/index.mjs:5:9
    at getESLintBaseRule (file:///D:/geobox/node_modules/.pnpm/eslint-plugin-unused-imports@4.1.1_@typescript-eslint+eslint-plugin@8.0.1_@typescript-eslint+_cdfts5mwz3dmzs6enchjkop4n4/node_modules/eslint-plugin-unused-imports/dist/index.mjs:104:18)
    at getBaseRule (file:///D:/geobox/node_modules/.pnpm/eslint-plugin-unused-imports@4.1.1_@typescript-eslint+eslint-plugin@8.0.1_@typescript-eslint+_cdfts5mwz3dmzs6enchjkop4n4/node_modules/eslint-plugin-unused-imports/dist/index.mjs:98:14)
    at file:///D:/geobox/node_modules/.pnpm/eslint-plugin-unused-imports@4.1.1_@typescript-eslint+eslint-plugin@8.0.1_@typescript-eslint+_cdfts5mwz3dmzs6enchjkop4n4/node_modules/eslint-plugin-unused-imports/dist/index.mjs:109:72
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadFlatConfigFile (D:\geobox\node_modules\.pnpm\eslint@9.8.0\node_modules\eslint\lib\eslint\eslint.js:317:21)
    at async calculateConfigArray (D:\geobox\node_modules\.pnpm\eslint@9.8.0\node_modules\eslint\lib\eslint\eslint.js:397:28)
    at async ESLint.lintFiles (D:\geobox\node_modules\.pnpm\eslint@9.8.0\node_modules\eslint\lib\eslint\eslint.js:829:25)
    at async Object.execute (D:\geobox\node_modules\.pnpm\eslint@9.8.0\node_modules\eslint\lib\cli.js:501:23)
```

**Comment by jessekrubin** [comment]
@antfu looks like I created this issue LITERALLY AT THE EXACT SAME MOMENT you released 4.1.2... It looks good to me!
