### ISSUE TITLE
Cannot use 'in' operator to search for 'type' in undefined

### ISSUE THREAD

**Issue by FedeMadoery** [sweepline/eslint-plugin-unused-imports#98]
I'm facing the following issue on a NextJs project, I guess that if `variableOrIdentifierOrName` could be undefined, maybe we need a check on it? I can not find why it is undefined 

```
if (typeof variableOrIdentifierOrName !== 'string' &&
            !('type' in variableOrIdentifierOrName)) { /// <--- Here
            variableOrIdentifierOrName.eslintUsed = true;
            return;
        }
```

# EsLint config

```
{
  "extends": "next/core-web-vitals",
  "parserOptions": {
    "project": "tsconfig.json",
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint/eslint-plugin", "unused-imports", "sort-keys-fix", "sort-destructure-keys", "jsx-a11y"],
  "rules": {
    "@next/next/no-html-link-for-pages": "off",
    "no-unused-vars": "warn",
    "unused-imports/no-unused-imports": "error",
    "unused-imports/no-unused-vars": "warn",
    "react/jsx-sort-props": 2,
    "sort-destructure-keys/sort-destructure-keys": 2,
    "sort-keys-fix/sort-keys-fix": "warn",
    "import/order": [
      "error",
      {
        "newlines-between": "always",
        "alphabetize": { "order": "desc" }
      }
    ],
    "max-len": ["warn", { "code": 200, "ignorePattern": "d=\"([\\s\\S]*?)\"" }]
  }
}

```
# Stacktrace:

```
TypeError: Cannot use 'in' operator to search for 'type' in undefined
Occurred while linting /.../src/configs/web3.ts:1
Rule: "unused-imports/no-unused-imports"
    at UnusedVarsVisitor.markVariableAsUsed (/.../node_modules/.pnpm/@typescript-eslint+eslint-plugin@8.2.0_@typescript-eslint+parser@8.2.0_eslint@8.57.0_typescript@5.5.4/node_modules/@typescript-eslint/eslint-plugin/dist/util/collectUnusedVariables.js:92:22)
    at UnusedVarsVisitor.TSMappedType (/.../node_modules/.pnpm/@typescript-eslint+eslint-plugin@8.2.0_@typescript-eslint+parser@8.2.0_eslint@8.57.0_typescript@5.5.4/node_modules/@typescript-eslint/eslint-plugin/dist/util/collectUnusedVariables.js:235:14)
    at UnusedVarsVisitor.visit (/.../node_modules/.pnpm/@typescript-eslint+scope-manager@8.2.0/node_modules/@typescript-eslint/scope-manager/dist/referencer/VisitorBase.js:59:21)

```

web3.ts:1

```
import { RPCProviders, RPCProvidersENV, isGitHubActionBuild } from "@src/types/rpc-providers";
```

tsconfig.json

```
"paths": {
      "@/*": ["./*"],
      "@src/*": ["./src/*"]
    },
```

**Comment by antfu** [comment]
But the code you are referencing is not even in this repo... Please report to typescript-eslint with a proper reproduction.

**Comment by vaynevayne** [comment]
same issue
